version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: polybright
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      target: api
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/polybright
      JWT_SECRET: change-me-super-secret-32chars
      ORIGIN: http://web:3000
      SESSION_COOKIE_NAME: polybright.sid
      TIMEZONE: Asia/Manila
      CURRENCY: PHP
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/api/healthz']
      interval: 30s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      target: web
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE: http://localhost:4000/api
    ports:
      - '3000:3000'
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  db-data:
